name: CI

on: [push, pull_request]

jobs:

  checks:
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
        py: ["3.10", "3.11", "3.12", "pypy3.10"]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        pip install --disable-pip-version-check --no-cache-dir uv
        uv sync --group dev
    - name: Run checks with ruff
      run: |
        uv run ruff check

  tests:
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
        py: ["3.10", "3.11", "3.12", "pypy3.10"]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }}

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install --disable-pip-version-check --no-cache-dir uv
        uv sync --group test

    - name: Test with pytest
      run: |
        uv run pytest

  publish:
    needs: [checks, tests]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Build the package
      run: |
        pip install --disable-pip-version-check --no-cache-dir uv
        uv build

    - name: Publish to PyPI
      continue-on-error: true
      run: |
        uv publish
